### ISSUE TITLE
GREAT - dry code

### ISSUE THREAD

**Issue by franfranfranfran** [saas-0326/prj-rev-bwfs-tea-cozy#1]
https://github.com/saas-0326/prj-rev-bwfs-tea-cozy/blob/master/teacozy/resources/css/style.css#L84-L88

excellent implementation of DRY principles in using the general flex-container class to apply common styling to many sections.

**Comment by saas-0326** [comment]
Thanks for noticing it. At first I did it independently until I got the exact result I wanted on each section, and at the end I went back to review the different components and grouped the similar ones.
