### ISSUE TITLE
GREAT - organization

### ISSUE THREAD

**Issue by franfranfranfran** [saas-0326/prj-rev-bwfs-tea-cozy#2]
excellent job using consistent indentation and comments to help keep your code organized and readable. make sure to continue through the rest of your html with the comments, looks like you just have them for the first two content sections and the footer.

**Comment by saas-0326** [comment]
I've always been a huge fan of indentation so I'm very careful to do it good, also I use some plugins to help with that.
About the comments you're right, I forgot some of them through my code
