### ISSUE TITLE
GREAT - semantic elements

### ISSUE THREAD

**Issue by franfranfranfran** [saas-0326/prj-rev-bwfs-tea-cozy#3]
great use of the header, nav, and footer semantic tags. check out this info to see some other examples of tags you could use in future projects - https://www.w3schools.com/html/html5_semantic_elements.asp

**Comment by saas-0326** [comment]
Thanks for the tip! I was wondering what the difference could be and decided to do it this way since it was a bit more descriptive. I'll be sure to review the link you gave me and remember all semantic tags I can.
