### ISSUE TITLE
GREAT - alt attribute

### ISSUE THREAD

**Issue by franfranfranfran** [saas-0326/prj-rev-bwfs-tea-cozy#4]
https://github.com/saas-0326/prj-rev-bwfs-tea-cozy/blob/master/teacozy/index.html#L52
etc...

nice work including the alt attribute to make your page more accessible to a wider variety of users

**Comment by saas-0326** [comment]
Thanks, it was a tip given to me on the last reviewed project and it seemed a great advice so I decided to do it always.
