### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by franfranfranfran** [saas-0326/prj-rev-bwfs-tea-cozy#5]
**GRADE**: Exceeds Expectations

**SUMMARY**: Excellent work on this project! The site itself looks great and you did an excellent job keeping both the project folder and the code itself neat, organized, and readable. Nice work keeping your code DRY and using flex display to help align items throughout the page. 

I don't really have anything to report as far as errors, your code looks great. Comparing to the example page given [here](https://www.codecademy.com/courses/freelance1-u4/projects/tea-cozy?program_content_id=103e02e37b36102efba7973dab4b22aa&program_id=acbc496d9b1db33b5692edbe890c44e1), it does seem very similar. If you are using devtools, try to rely on it a little less before you get the page setup. That'll let you focus on honing in the key skills required to plan the structure of a page before you start coding it.

From here you are in a great place to explore what Bootstrap has to offer. Here's some more info on how to create a flashier navigation bar by including Bootstrap in your project - https://v4-alpha.getbootstrap.com/components/navbar/

Keep up the good work!

**Comment by saas-0326** [comment]
Thank you very much! I really appreciate your comments.
I'll continue exploring Bootstrap and the responsive design.
